# Generated by Django 5.0 on 2024-01-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='urgency',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Very-High')], default=0),
        ),
    ]
